Repository ita-social-projects/Car-Back-End, pull requests merged in 2021-02, with the labels that each got.

#211 Closed #8 - Applicant profile
  Car.Backend/Car.Domain/Services/Implementation/UserService.cs
  Car.Backend/Car.Domain/Services/Interfaces/IUserService.cs
  Car.Backend/Car.UnitTests/Controllers/UserControllerTest.cs
  Car.Backend/Car.UnitTests/Services/UserServiceTest.cs
  Car.Backend/Car.WebApi/Car.WebApi.xml
  Car.Backend/Car.WebApi/Controllers/UserController.cs
Labels: story

#220 Closes #215 journey manage applicants
  Car.Backend/.editorconfig
  Car.Backend/Car.Data/Entities/Journey.cs
  Car.Backend/Car.Data/Infrastructure/Repository.cs
  Car.Backend/Car.Data/Infrastructure/UnitOfWork.cs
  Car.Backend/Car.Data/Interfaces/IRepository.cs
  Car.Backend/Car.Data/Interfaces/IUnitOfWork.cs
  Car.Backend/Car.Data/Migrations/20210122125638_AddUserChatsEntity.cs
  Car.Backend/Car.Data/Migrations/20210203114440_AddedChatEntity.cs
  Car.Backend/Car.Domain/Car.Domain.csproj
  Car.Backend/Car.Domain/Dto/ParticipantDto.cs
  Car.Backend/Car.Domain/Services/Implementation/JourneyService.cs
  Car.Backend/Car.Domain/Services/Interfaces/IJourneyService.cs
  Car.Backend/Car.UnitTests/Services/JourneyServiceTest.cs
  Car.Backend/Car.WebApi/Car.WebApi.csproj
  Car.Backend/Car.WebApi/Car.WebApi.xml
  Car.Backend/Car.WebApi/Controllers/JourneyController.cs
  Car.Backend/Car.WebApi/Properties/launchSettings.json
Labels: subtask

#243 Closed #242 - Car service and journey service fixed
  Car.Backend/Car.Domain/Services/Implementation/CarService.cs
  Car.Backend/Car.Domain/Services/Implementation/JourneyService.cs
  Car.Backend/Car.Domain/Services/Implementation/Strategy/CarEntityStrategy.cs
  Car.Backend/Car.Domain/Services/Interfaces/ICarService.cs
  Car.Backend/Car.WebApi/Car.WebApi.xml
  Car.Backend/Car.WebApi/Controllers/CarController.cs
Labels: bug

#258 Closed #257 - Add journey count to DTO
  Car.Backend/Car.Data/SeedData/SeedData.cs
  Car.Backend/Car.Domain/Extensions/CarServiceExtension.cs
  Car.Backend/Car.Domain/Extensions/JourneyServiceExtension.cs
  Car.Backend/Car.Domain/Services/Implementation/BrandService.cs
  Car.Backend/Car.Domain/Services/Implementation/CarService.cs
  Car.Backend/Car.Domain/Services/Implementation/ChatService.cs
  Car.Backend/Car.Domain/Services/Implementation/GoogleDriveService.cs
  Car.Backend/Car.Domain/Services/Implementation/ImageService.cs
  Car.Backend/Car.Domain/Services/Implementation/ModelService.cs
  Car.Backend/Car.Domain/Services/Implementation/NotificationService.cs
  Car.Backend/Car.WebApi/Controllers/BrandController.cs
  Car.Backend/Car.WebApi/Controllers/CarController.cs
  Car.Backend/Car.WebApi/Controllers/ChatController.cs
  Car.Backend/Car.WebApi/Controllers/JourneyController.cs
  Car.Backend/Car.WebApi/Controllers/LoginController.cs
  Car.Backend/Car.WebApi/Controllers/ModelController.cs
  Car.Backend/Car.WebApi/Controllers/NotificationController.cs
  Car.Backend/Car.WebApi/Hubs/ChatHub.cs
  Car.Backend/Car.WebApi/Properties/ServiceDependencies/Car-Project-Backup - Web Deploy/appInsights1.arm.json
  Car.Backend/Car.WebApi/Properties/ServiceDependencies/Car-Project-Backup - Web Deploy/profile.arm.json
  Car.Backend/Car.WebApi/Properties/ServiceDependencies/Car-Project-Backup - Web Deploy/signalr1.arm.json
  Car.Backend/Car.WebApi/Properties/serviceDependencies.Car-Project-Backup - Web Deploy.json
  Car.Backend/Car.WebApi/Properties/serviceDependencies.json
Labels: task

#271 Closed #270 - Update Models & Brands
  Car.Backend/Car.Data/SeedData/SeedData.cs
Labels: task
